### ISSUE TITLE
Cannot parse

### ISSUE THREAD

**Issue by tspeidel** [noe/whatsapp2md#2]
I'm running into errors converting a chat. The exported datetime and line format are of the following type:

`2021-02-13, 17:21 - SenderName: IMG-20210101-WA0000.jpg (file attached)`

The errors are as follows:
`Traceback (most recent call last):
  File "whatsapp2md.py", line 162, in <module>
    main()
  File "whatsapp2md.py", line 144, in main
    entries = parse_lines(f)
  File "whatsapp2md.py", line 115, in parse_lines
    for lineno, line in enumerate(lines, 1):
  File "C:\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1392: character maps to <undefined>`

<br>

I'm running Python 3.7.6. My Win Locale is:

`LCID             Name             DisplayName`
`----             ----             -----------`
`4105             en-CA            English (Canada)`

***
Are there any lines in `whatsapp2md.py` I should change?

**Comment by noe** [comment]
Can you try setting the environment variable `PYTHONIOENCODING` to `utf_8` before running the script?:

```
set PYTHONIOENCODING=utf_8
```

**Comment by noe** [comment]
Also, I modified the script to set the input encoding. Can you test with the latest version?

**Comment by tspeidel** [comment]
Thanks for looking into this. I'm still getting errors (after setting UTF-8 and redownloading the script):

```
Traceback (most recent call last):
  File "whatsapp2md.py", line 170, in <module>
    main()
  File "whatsapp2md.py", line 152, in main
    entries = parse_lines(f)
  File "whatsapp2md.py", line 132, in parse_lines
    raise ValueError(msg.format(lineno))
ValueError: Malformed file: line 1 is a continuation of no previous line
```

<br>

I call the script:

```
python whatsapp2md.py "C:/Users/LongPathToDir/chat.txt" > "C:/Users/LongPathToDir/chat.md"
```

The very first line of chat.txt is:
`2020-12-24, 21:18 - Fname Lname: IMG-20201224-WA0022.jpg (file attached)`

**Comment by noe** [comment]
I added support for that date format. Please check again.

**Comment by tspeidel** [comment]
Much better thanks! 
Still getting some character encoding errors, but at least I get an .md!
```
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 589-592: character maps to <undefined>
```

It would be a nice feature to have the name of the sender included in the md. If I was better in Python I would contribute to it.
Thanks for sharing this useful script.

**Comment by noe** [comment]
The format may have changed since I created the script, because originally it was able to extract the sender and include it in the .md file. Also, I am not sure if the format is consistent across platforms. If you can share a chat dump, I may be able to fix the script.

**Comment by tspeidel** [comment]
Here 's a sample:

2020-12-24, 21:18 - Micky Mouse: IMG-20201224-WA0029.jpg (file attached)
2020-12-25, 02:23 - Daisy Duck: Merry Christmas!
2020-12-25, 08:07 - Pluto: Hello my dears, have a nice day 😘👍🏽😀
2020-12-25, 10:02 - Peter Pan: Wow great to hear! 👏🏻👏🏻👏🏻
