### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by ashishbhateja** [noe/whatsapp2md#6]
I keep getting this error message:

Traceback (most recent call last):
  File "whatsapp2md.py", line 181, in <module>
    main()
  File "whatsapp2md.py", line 163, in main
    entries = parse_lines(f)
  File "whatsapp2md.py", line 143, in parse_lines
    raise ValueError(msg.format(lineno, line))
ValueError: Malformed file: line 1 ([1/6/16, 9:58:07 PM] R&R: ‎Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them.) is a continuation of no previous line.

**Comment by noe** [comment]
Thanks for the feedback. The format of the exported chats has been changing since I created this project. I will add a note in the readme.

**Comment by ashishbhateja** [comment]
> The format of the exported chats has been changing

Is there a fix planned for the current format of the exported chats?
